{
 "title": "Application Whitebox Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "DevOps Experience", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DevOps Heroes",
   "type": "text",
   "gridPos": { "h": 12, "w": 19, "x": 0, "y": 1 },
   "options": {
    "content": "<img src=\"https://raw.githubusercontent.com/marcelo-devsres/observabilidade-episodio-2-metricas/main/static/devops-experience.png\" />"
   }
  },
  {
   "title": "Métricas com Prometheus",
   "type": "text",
   "gridPos": { "h": 12, "w": 3, "x": 19, "y": 1 },
   "options": {
    "content": "<img src=\"https://raw.githubusercontent.com/marcelo-devsres/observabilidade-episodio-2-metricas/main/static/marcelo.png\" />"
   }
  },
  { "title": "Gauges", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Sistema Operacional - Memória",
   "type": "gauge",
   "description": "Sistema Operacional - Memória",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sistema Operacional - Disco",
   "type": "gauge",
   "description": "Sistema Operacional - Disco",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - node_filesystem_avail_bytes{mountpoint=\"/mnt/c\"} / node_filesystem_size_bytes{mountpoint=\"/mnt/c\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sistema Operacional",
   "type": "timeseries",
   "description": "Versão da aplicação",
   "gridPos": { "h": 8, "w": 11, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU {{cpu}}"
    },
    {
     "expr": "100 - (avg (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "Agregado"
    }
   ]
  },
  { "title": "Counters - simples", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Counter - HTTP Requests (Total)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(http_requests_total)", "legendFormat": "HTTP (soma)" }
   ]
  },
  {
   "title": "Counter - HTTP Requests (Total)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 15, "x": 5, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "HTTP {{code}}" }
   ]
  },
  {
   "title": "Counter - HTTP Requests (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 31 },
   "targets": [
    { "expr": "sum(http_requests_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Counter - HTTP Requests (200)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 31 },
   "targets": [
    {
     "expr": "http_requests_total{code=\"200\"}",
     "legendFormat": "HTTP {{code}}"
    }
   ]
  },
  {
   "title": "Counter - HTTP Requests (404)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 31 },
   "targets": [
    {
     "expr": "http_requests_total{code=\"404\"}",
     "legendFormat": "HTTP {{code}}"
    }
   ]
  },
  {
   "title": "Counter - HTTP Requests (500)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 31 },
   "targets": [
    {
     "expr": "http_requests_total{code=\"500\"}",
     "legendFormat": "HTTP {{code}}"
    }
   ]
  },
  { "title": "Counter - Agregações", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Consulta:",
   "type": "text",
   "gridPos": { "h": 3, "w": 20, "x": 0, "y": 40 },
   "options": {
    "content": "```\nhttp_requests_total / on () group_left () sum(http_requests_total)\n```\n"
   }
  },
  {
   "title": "Counter - HTTP Requests (Total)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total / on () group_left () sum(http_requests_total)",
     "legendFormat": "HTTP {{code}}"
    }
   ]
  },
  {
   "title": "Counter - HTTP Requests (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "http_requests_total / on () group_left () sum(http_requests_total)",
     "legendFormat": "HTTP {{code}}"
    }
   ]
  },
  {
   "title": "Consulta:",
   "type": "text",
   "gridPos": { "h": 3, "w": 20, "x": 0, "y": 59 },
   "options": {
    "content": "```\nrate(http_requests_total{code=\"XYZ\"}[$__rate_interval])\n"
   }
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "rate(http_requests_total{code=\"200\"}[$__rate_interval])",
     "legendFormat": "HTTP {{code}}"
    }
   ]
  },
  {
   "title": "HTTP Requests (200) per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 62 },
   "targets": [
    {
     "expr": "rate(http_requests_total{code=\"200\"}[$__rate_interval])",
     "legendFormat": "HTTP {{code}}"
    }
   ]
  },
  {
   "title": "HTTP Requests (404) per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 62 },
   "targets": [
    {
     "expr": "rate(http_requests_total{code=\"404\"}[$__rate_interval])",
     "legendFormat": "HTTP {{code}}"
    }
   ]
  },
  {
   "title": "HTTP Requests (500) per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 62 },
   "targets": [
    {
     "expr": "rate(http_requests_total{code=\"500\"}[$__rate_interval])",
     "legendFormat": "HTTP {{code}}"
    }
   ]
  },
  {
   "title": "Histogram - Count / Sum",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Requests Duration (Count)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "http_request_duration_seconds_count",
       "legendFormat": "Request Duration (count)"
      }
     ]
    },
    {
     "title": "HTTP Request Duration (Sum)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 35 },
     "targets": [
      {
       "expr": "http_request_duration_seconds_sum",
       "legendFormat": "Request Duration (count)"
      }
     ]
    },
    {
     "title": "Rate Request Duration (Count)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "rate(http_request_duration_seconds_count[$__rate_interval])",
       "legendFormat": "Request Duration (count)"
      }
     ]
    },
    {
     "title": "Rate Request Duration (Sum)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 43 },
     "targets": [
      {
       "expr": "rate(http_request_duration_seconds_sum[$__rate_interval])",
       "legendFormat": "Request Duration (count)"
      }
     ]
    },
    {
     "title": "Consulta:",
     "type": "text",
     "gridPos": { "h": 3, "w": 20, "x": 0, "y": 51 },
     "options": {
      "content": "```\nrate(http_request_duration_seconds_sum[$__rate_interval])/rate(http_request_duration_seconds_count[$__rate_interval])\n```\n"
     }
    },
    {
     "title": "Duração média por segundo",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 20, "x": 0, "y": 54 },
     "targets": [
      {
       "expr": "rate(http_request_duration_seconds_sum[$__rate_interval])/rate(http_request_duration_seconds_count[$__rate_interval])",
       "legendFormat": "Duração média"
      }
     ]
    }
   ]
  },
  {
   "title": "Histogram - Buckets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Request Duration (s) - Buckets",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 22, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "http_request_duration_seconds_bucket",
       "legendFormat": "Request<={{le}}"
      }
     ]
    },
    {
     "title": "HTTP Request Duration (s) - Histogram",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 22, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "sum without(endpoint) (http_request_duration_seconds_bucket)",
       "legendFormat": "<={{le}}"
      }
     ]
    },
    {
     "title": "HTTP Request Duration (s) - Histogram",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 22, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "sum without(endpoint) (http_request_duration_seconds_bucket{le=\"0.05\"})",
       "legendFormat": "X <=0.05"
      },
      {
       "expr": "sum without(endpoint) ( http_request_duration_seconds_bucket{le=\"0.1\"} - ignoring (le) http_request_duration_seconds_bucket{le=\"0.05\"} )",
       "legendFormat": "0.05< X <=0.1"
      },
      {
       "expr": "sum without(endpoint) ( http_request_duration_seconds_bucket{le=\"0.2\"} - ignoring (le) http_request_duration_seconds_bucket{le=\"0.1\"} )",
       "legendFormat": "0.1< X <=0.2"
      },
      {
       "expr": "sum without(endpoint) ( http_request_duration_seconds_bucket{le=\"0.3\"} - ignoring (le) http_request_duration_seconds_bucket{le=\"0.2\"} )",
       "legendFormat": "0.2< X <=0.3"
      },
      {
       "expr": "sum without(endpoint) ( http_request_duration_seconds_bucket{le=\"0.4\"} - ignoring (le) http_request_duration_seconds_bucket{le=\"0.3\"} )",
       "legendFormat": "0.3< X <=0.4"
      },
      {
       "expr": "sum without(endpoint) ( http_request_duration_seconds_bucket{le=\"0.5\"} - ignoring (le) http_request_duration_seconds_bucket{le=\"0.4\"} )",
       "legendFormat": "0.4< X <=0.5"
      },
      {
       "expr": "sum without(endpoint) ( http_request_duration_seconds_bucket{le=\"0.75\"} - ignoring (le) http_request_duration_seconds_bucket{le=\"0.5\"} )",
       "legendFormat": "0.5< X <=0.75"
      },
      {
       "expr": "sum without(endpoint) ( http_request_duration_seconds_bucket{le=\"1\"} - ignoring (le) http_request_duration_seconds_bucket{le=\"0.75\"} )",
       "legendFormat": "0.75< X <=1"
      },
      {
       "expr": "sum without(endpoint) ( http_request_duration_seconds_bucket{le=\"2.5\"} - ignoring (le) http_request_duration_seconds_bucket{le=\"1\"} )",
       "legendFormat": "1< X <=2.5"
      },
      {
       "expr": "sum without(endpoint) ( http_request_duration_seconds_bucket{le=\"+Inf\"} - ignoring (le) http_request_duration_seconds_bucket{le=\"2.5\"} )",
       "legendFormat": "X >2.5"
      }
     ]
    },
    {
     "title": "Duração de 95% das minhas requisições",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 22, "x": 0, "y": 56 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(http_request_duration_seconds_bucket[$__rate_interval])))",
       "legendFormat": "Request<={{le}}"
      }
     ]
    },
    {
     "title": "Consulta:",
     "type": "text",
     "gridPos": { "h": 3, "w": 22, "x": 0, "y": 66 },
     "options": {
      "content": "```\nhistogram_quantile(0.99, sum by(le) (rate(http_request_duration_seconds_bucket[$__rate_interval])))\n```"
     }
    },
    {
     "title": "Percentis",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 22, "x": 0, "y": 69 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(http_request_duration_seconds_bucket[$__rate_interval])))",
       "legendFormat": "Percentil 99%"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(http_request_duration_seconds_bucket[$__rate_interval])))",
       "legendFormat": "Percentil 95"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le) (rate(http_request_duration_seconds_bucket[$__rate_interval])))",
       "legendFormat": "Percentil 90"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(http_request_duration_seconds_bucket[$__rate_interval])))",
       "legendFormat": "Percentil 50"
      }
     ]
    }
   ]
  },
  {
   "title": "SLA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests DENTRO do SLA",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "http_request_duration_seconds_bucket{le=\"0.5\"}",
       "legendFormat": "Requests dentro do SLA"
      }
     ]
    },
    {
     "title": "Requests FORA do SLA",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "expr": "http_request_duration_seconds_bucket{le=\"+Inf\"} - ignoring (le) http_request_duration_seconds_bucket{le=\"0.5\"} ",
       "legendFormat": "Requests fora do SLA"
      }
     ]
    },
    {
     "title": "Consulta:",
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 15 },
     "options": {
      "content": "```\n(http_request_duration_seconds_bucket{le=\"0.5\"} / ignoring(le) http_request_duration_seconds_count)\n```"
     }
    },
    {
     "title": "Percentual de requisições dentro do SLA",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(http_request_duration_seconds_bucket{le=\"0.5\"} / ignoring(le) http_request_duration_seconds_count)",
       "legendFormat": "Requests dentro do SLA"
      }
     ]
    }
   ]
  },
  {
   "title": "Bônus: Summaries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consulta:",
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 8 },
     "options": {
      "content": "```\nhttp_request_summary_duration_seconds\n```"
     }
    },
    {
     "title": "Percentis (Summary)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "http_request_summary_duration_seconds",
       "legendFormat": "Quantil: {{quantile}}"
      }
     ]
    }
   ]
  }
 ]
}